package ptest

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"sync/atomic"
	"testing"
	"time"

	"github.com/portablesql/psql"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// Integration tests for autoinc columns, BulkInsert and TxWithOptions. They
// run on the engine selected by PSQL_TEST_DSN, SQLite in memory by default.

type CorePgAutoItem struct {
	psql.Name `sql:"core_pg_auto_item"`
	ID        int64  `sql:",key=PRIMARY,autoinc"`
	Label     string `sql:",type=VARCHAR,size=64"`
}

// createAutoTable creates the autoinc test table with explicit DDL on MySQL
// and PostgreSQL so the test does not depend on the driver rendering the
// autoinc attribute; SQLite gets it from the automatic schema check (an
// INTEGER PRIMARY KEY is the rowid).
func createAutoTable(t *testing.T, ctx context.Context, be *psql.Backend, name string) {
	t.Helper()
	switch be.Engine() {
	case psql.EngineMySQL:
		require.NoError(t, psql.Q("CREATE TABLE `"+name+"` (`ID` BIGINT NOT NULL AUTO_INCREMENT, `Label` VARCHAR(64) NOT NULL, PRIMARY KEY (`ID`))").Exec(ctx))
	case psql.EnginePostgreSQL:
		require.NoError(t, psql.Q(`CREATE TABLE "`+name+`" ("ID" BIGINT GENERATED BY DEFAULT AS IDENTITY, "Label" VARCHAR(64) NOT NULL, PRIMARY KEY ("ID"))`).Exec(ctx))
	}
}

func TestCorePgAutoIncInsert(t *testing.T) {
	be := getTestBackend(t)
	ctx := be.Plug(context.Background())
	_ = psql.Q(`DROP TABLE IF EXISTS "core_pg_auto_item"`).Exec(ctx)
	defer func() { _ = psql.Q(`DROP TABLE IF EXISTS "core_pg_auto_item"`).Exec(ctx) }()
	createAutoTable(t, ctx, be, "core_pg_auto_item")

	a := &CorePgAutoItem{Label: "a"}
	require.NoError(t, psql.Insert(ctx, a))
	assert.NotZero(t, a.ID, "autoinc key must be populated after Insert")
	b := &CorePgAutoItem{Label: "b"}
	require.NoError(t, psql.Insert(ctx, b))
	assert.NotZero(t, b.ID)
	assert.NotEqual(t, a.ID, b.ID)

	// an explicit id is kept
	c := &CorePgAutoItem{ID: 1000, Label: "c"}
	require.NoError(t, psql.Insert(ctx, c))
	assert.Equal(t, int64(1000), c.ID)

	// one call mixing generated and explicit ids
	items := []*CorePgAutoItem{{Label: "d"}, {ID: 2000, Label: "e"}, {Label: "f"}}
	require.NoError(t, psql.Insert(ctx, items...))
	assert.NotZero(t, items[0].ID)
	assert.Equal(t, int64(2000), items[1].ID)
	assert.NotZero(t, items[2].ID)
	assert.NotEqual(t, items[0].ID, items[2].ID)

	got, err := psql.Get[CorePgAutoItem](ctx, map[string]any{"ID": b.ID})
	require.NoError(t, err)
	assert.Equal(t, "b", got.Label)

	// Update never writes the autoinc column
	got.Label = "bb"
	require.NoError(t, psql.Update(ctx, got))
	again, err := psql.Get[CorePgAutoItem](ctx, map[string]any{"ID": b.ID})
	require.NoError(t, err)
	assert.Equal(t, "bb", again.Label)

	cnt, err := psql.Count[CorePgAutoItem](ctx, nil)
	require.NoError(t, err)
	assert.Equal(t, 6, cnt)
}

type CorePgBulkItem struct {
	psql.Name `sql:"core_pg_bulk_item"`
	ID        int64  `sql:",key=PRIMARY,autoinc"`
	Label     string `sql:",type=VARCHAR,size=64"`
	Rank      int64
}

var corePgBulkHooks struct {
	before atomic.Int32
	after  atomic.Int32
}

func (b *CorePgBulkItem) BeforeInsert(context.Context) error {
	corePgBulkHooks.before.Add(1)
	if b.Rank < 0 {
		b.Rank = 0
	}
	return nil
}

func (b *CorePgBulkItem) AfterInsert(context.Context) error {
	corePgBulkHooks.after.Add(1)
	return nil
}

func TestCorePgBulkInsertRoundTrip(t *testing.T) {
	be := getTestBackend(t)
	ctx := be.Plug(context.Background())
	_ = psql.Q(`DROP TABLE IF EXISTS "core_pg_bulk_item"`).Exec(ctx)
	defer func() { _ = psql.Q(`DROP TABLE IF EXISTS "core_pg_bulk_item"`).Exec(ctx) }()
	switch be.Engine() {
	case psql.EngineMySQL:
		require.NoError(t, psql.Q("CREATE TABLE `core_pg_bulk_item` (`ID` BIGINT NOT NULL AUTO_INCREMENT, `Label` VARCHAR(64) NOT NULL, `Rank` BIGINT NOT NULL, PRIMARY KEY (`ID`))").Exec(ctx))
	case psql.EnginePostgreSQL:
		require.NoError(t, psql.Q(`CREATE TABLE "core_pg_bulk_item" ("ID" BIGINT GENERATED BY DEFAULT AS IDENTITY, "Label" VARCHAR(64) NOT NULL, "Rank" BIGINT NOT NULL, PRIMARY KEY ("ID"))`).Exec(ctx))
	}

	corePgBulkHooks.before.Store(0)
	corePgBulkHooks.after.Store(0)

	const n = 1200
	rows := make([]*CorePgBulkItem, n)
	for i := range rows {
		rows[i] = &CorePgBulkItem{Label: fmt.Sprintf("row-%04d", i), Rank: -1}
	}
	require.NoError(t, psql.BulkInsert(ctx, rows))
	assert.Equal(t, int32(n), corePgBulkHooks.before.Load(), "BeforeInsert once per row")
	assert.Equal(t, int32(n), corePgBulkHooks.after.Load(), "AfterInsert once per row")

	cnt, err := psql.Count[CorePgBulkItem](ctx, nil)
	require.NoError(t, err)
	assert.Equal(t, n, cnt)

	all, err := psql.Fetch[CorePgBulkItem](ctx, nil, psql.Sort(psql.S("ID", "ASC")))
	require.NoError(t, err)
	require.Len(t, all, n)
	for i, r := range all {
		assert.Equal(t, fmt.Sprintf("row-%04d", i), r.Label, "rows are stored in order")
		assert.Equal(t, int64(0), r.Rank, "BeforeInsert changes are written")
	}

	if be.Engine() != psql.EngineSQLite {
		// PostgreSQL (RETURNING) and MySQL (LastInsertId + index) populate the
		// generated keys; SQLite does not guarantee contiguous rowids
		for i, r := range rows {
			require.NotZero(t, r.ID, "row %d key must be populated", i)
			assert.Equal(t, all[i].ID, r.ID, "row %d key must match the stored one", i)
		}
	}

	// explicit ids and generated ones in one call, batches sized by option
	// (explicit ids are far apart: SQLite and MySQL generate max(id)+1)
	corePgBulkHooks.before.Store(0)
	more := []*CorePgBulkItem{{ID: 100000, Label: "x"}, {Label: "y"}, {ID: 200000, Label: "z"}}
	require.NoError(t, psql.BulkInsert(ctx, more, psql.BulkBatchSize(1), psql.BulkNoHooks()))
	assert.Equal(t, int32(0), corePgBulkHooks.before.Load(), "BulkNoHooks skips hooks")
	cnt, err = psql.Count[CorePgBulkItem](ctx, nil)
	require.NoError(t, err)
	assert.Equal(t, n+3, cnt)
	y, err := psql.Get[CorePgBulkItem](ctx, map[string]any{"Label": "y"})
	require.NoError(t, err)
	assert.NotZero(t, y.ID)

	// BulkIgnore skips conflicting rows
	dup := []*CorePgBulkItem{{ID: 100000, Label: "dup"}, {ID: 300000, Label: "new"}}
	require.NoError(t, psql.BulkInsert(ctx, dup, psql.BulkIgnore(), psql.BulkNoHooks()))
	cnt, err = psql.Count[CorePgBulkItem](ctx, nil)
	require.NoError(t, err)
	assert.Equal(t, n+4, cnt)
	x, err := psql.Get[CorePgBulkItem](ctx, map[string]any{"ID": 100000})
	require.NoError(t, err)
	assert.Equal(t, "x", x.Label, "existing row must be untouched")

	// without BulkIgnore the conflict is an error
	err = psql.BulkInsert(ctx, []*CorePgBulkItem{{ID: 100000, Label: "dup"}}, psql.BulkNoHooks())
	require.Error(t, err)
	assert.True(t, psql.IsDuplicate(err), "duplicate error must be classified: %v", err)

	// inside a transaction, a rolled back bulk insert leaves nothing behind
	err = psql.Tx(ctx, func(txCtx context.Context) error {
		if err := psql.BulkInsert(txCtx, []*CorePgBulkItem{{Label: "tx1"}, {Label: "tx2"}}, psql.BulkNoHooks()); err != nil {
			return err
		}
		return errors.New("abort")
	})
	assert.EqualError(t, err, "abort")
	cnt, err = psql.Count[CorePgBulkItem](ctx, nil)
	require.NoError(t, err)
	assert.Equal(t, n+4, cnt)
}

type CorePgTxItem struct {
	psql.Name `sql:"core_pg_tx_item"`
	ID        int64  `sql:",key=PRIMARY"`
	Label     string `sql:",type=VARCHAR,size=64"`
}

func TestCorePgTxWithOptions(t *testing.T) {
	be := getTestBackend(t)
	ctx := be.Plug(context.Background())
	_ = psql.Q(`DROP TABLE IF EXISTS "core_pg_tx_item"`).Exec(ctx)
	defer func() { _ = psql.Q(`DROP TABLE IF EXISTS "core_pg_tx_item"`).Exec(ctx) }()
	require.NoError(t, psql.Insert(ctx, &CorePgTxItem{ID: 1, Label: "seed"}))

	// commit
	calls := 0
	opts := &psql.TxOptions{MaxRetries: 2, Backoff: func(int) time.Duration { return 0 }}
	err := psql.TxWithOptions(ctx, opts, func(txCtx context.Context) error {
		calls++
		return psql.Insert(txCtx, &CorePgTxItem{ID: 2, Label: "committed"})
	})
	require.NoError(t, err)
	assert.Equal(t, 1, calls, "a successful callback runs once")
	cnt, err := psql.Count[CorePgTxItem](ctx, nil)
	require.NoError(t, err)
	assert.Equal(t, 2, cnt)

	// rollback on a plain error: not retried, returned as is
	calls = 0
	boom := errors.New("boom")
	err = psql.TxWithOptions(ctx, opts, func(txCtx context.Context) error {
		calls++
		if err := psql.Insert(txCtx, &CorePgTxItem{ID: 3, Label: "rolled back"}); err != nil {
			return err
		}
		return boom
	})
	assert.Equal(t, boom, err)
	assert.Equal(t, 1, calls)
	cnt, err = psql.Count[CorePgTxItem](ctx, nil)
	require.NoError(t, err)
	assert.Equal(t, 2, cnt)

	// a duplicate key is not retryable either
	err = psql.Tx(ctx, func(txCtx context.Context) error {
		return psql.Insert(txCtx, &CorePgTxItem{ID: 1, Label: "dup"})
	})
	require.Error(t, err)
	assert.True(t, psql.IsDuplicate(err))
	assert.False(t, psql.IsRetryable(err))
	assert.NotErrorIs(t, err, psql.ErrTxRetriesExhausted)

	// isolation / read-only options reach the driver
	if be.Engine() != psql.EngineSQLite {
		// SQLite's driver rejects read-only transactions
		err = psql.TxWithOptions(ctx, &psql.TxOptions{Isolation: sql.LevelSerializable, ReadOnly: true}, func(txCtx context.Context) error {
			_, err := psql.Count[CorePgTxItem](txCtx, nil)
			return err
		})
		require.NoError(t, err)
	}

	// nested call runs as a savepoint and does not retry
	inner := 0
	err = psql.TxWithOptions(ctx, opts, func(txCtx context.Context) error {
		if err := psql.Insert(txCtx, &CorePgTxItem{ID: 10, Label: "outer"}); err != nil {
			return err
		}
		nerr := psql.TxWithOptions(txCtx, opts, func(inCtx context.Context) error {
			inner++
			if err := psql.Insert(inCtx, &CorePgTxItem{ID: 11, Label: "inner"}); err != nil {
				return err
			}
			return errors.New("inner abort")
		})
		assert.EqualError(t, nerr, "inner abort")
		return nil
	})
	require.NoError(t, err)
	assert.Equal(t, 1, inner)
	cnt, err = psql.Count[CorePgTxItem](ctx, nil)
	require.NoError(t, err)
	assert.Equal(t, 3, cnt, "outer committed, inner rolled back to its savepoint")

	// context cancellation aborts a pending retry wait (only observable when
	// the engine reports retryable errors, so just check the plain path)
	cctx, cancel := context.WithCancel(ctx)
	cancel()
	err = psql.Tx(cctx, func(context.Context) error { return nil })
	require.Error(t, err, "a cancelled context cannot begin a transaction")
}
